sudo certbot certonly \
  -n \
  --webroot \
  --agree-tos \
  --email jxck@jxck.io \
  -w ../mozaic.fm \
  --expand \
  --force-renewal \
  --cert-name mozaic.fm \
  -d mozaic.fm \
  -d files.mozaic.fm \
  -d feed.mozaic.fm \
  -d labs.mozaic.fm
