sudo /home/linuxbrew/.linuxbrew/bin/certbot certonly \
  -n \
  --webroot \
  --agree-tos \
  --email jxck@jxck.io \
  -w ../www.jxck.io \
  --expand \
  --force-renewal \
  --preferred-profile shortlived \
  --cert-name jxck.io \
  -d jxck.io \
  -d www.jxck.io \
  -d blog.jxck.io \
  -d admin.jxck.io \
  -d files.jxck.io \
  -d logo.jxck.io \
  -d slide.jxck.io \
  -d book.jxck.io \
  -d labs.jxck.io \
  -d lab2.jxck.io \
  -d api.jxck.io \
  -d ws.jxck.io \
  -d zenn.jxck.io \
  -d reporting.jxck.io \
  -d http3.jxck.io \
  -d ipv6.jxck.io \
  -d ipv4.jxck.io \
  -d note.jxck.io