sudo /home/linuxbrew/.linuxbrew/bin/certbot certonly \
  -n \
  --dns-cloudflare \
  --dns-cloudflare-credentials /etc/letsencrypt/mozaic.fm.ini \
  --dns-cloudflare-propagation-seconds 30 \
  --agree-tos \
  --email jxck@jxck.io \
  --expand \
  --force-renewal \
  --preferred-profile shortlived \
  --cert-name mozaic.fm \
  -d mozaic.fm \
  -d www.mozaic.fm \
  -d files.mozaic.fm \
  -d feed.mozaic.fm \
  -d labs.mozaic.fm \
  -d wiki.mozaic.fm \
  -d vtt.mozaic.fm
