sudo certbot certonly \
  --manual \
  --agree-tos \
  --preferred-challenges dns \
  --manual \
  --agree-tos \
  --preferred-challenges dns \
  --force-renewal \
  --manual-public-ip-logging-ok \
  --cert-name localhost.jxck.io \
  --email admin@jxck.io \
  --domain localhost.jxck.io
