#!/bin/bash
./google-amp-update-cache.sh https://blog.jxck.io/entries/2021-05-11/end-of-ie.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2021-04-21/public-suffix-list.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2021-02-25/font-metrics-override.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2021-02-12/cache-control-must-understand.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2021-01-31/structured-field-values.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2020-12-31/end-of-2020.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2020-12-25/amp-signed-http-exchange.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2020-12-03/masonry-layout.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2020-11-19/how-to-track-web-standards.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2020-09-07/font-subsetting-with-puppeteer.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2020-09-01/webcodecs-webtransport-chat.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2020-08-15/selection-of-img-srcset.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2020-07-26/bundle-subresources.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2020-06-29/https-for-localhost.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2020-06-09/quic-transport.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2020-05-22/site-isolation.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2020-05-06/mozaic-v3-release.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2020-04-23/periodic-background-sync.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2020-03-27/scroll-to-search-result.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2020-02-25/end-of-idyllic-cookie.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2020-01-31/ads-for-blog.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2020-01-24/background-fetch.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2020-01-18/reporting.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2019-12-28/end-of-2019.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2019-11-12/webbundle.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2019-11-03/nuc-dev-server-port-forwarding.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2019-10-16/scroll-to-text-fragment.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2019-10-13/font-feature-settings.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2019-08-20/promise-allsettled-any.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2019-08-18/webtransport-and-webcodecs.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2019-08-14/nullish-coalescing-optional-chaining.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2019-06-16/display-locking.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2019-05-20/lazyloading.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2019-05-12/mozaic-bootcamp-2019.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2019-04-26/hyperlink-auditing-via-ping.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2019-03-14/private-class-field.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2019-01-27/trusted-types.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2019-01-19/cache-digest-status.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2019-01-15/next-web-conf-2019.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-12-31/end-of-2018.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-12-01/signed-http-exchanges.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-11-10/dark-mode-via-prefers-color-scheme.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-10-26/same-site-cookie.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-10-08/referrer-policy.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-09-15/next-web-conf-2019.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-07-24/clear-site-data.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-07-20/toggle-attribute.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-07-18/how-to-logging-monthly-web.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-05-15/webauthentication-api.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-05-01/layered-apis.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-04-30/redirect-to-pts.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-03-27/certificate-transparency.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-03-08/feature-policy-permission-delegation.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-02-13/web-font-woff2.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-01-17/freezing-user-agent-string.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-01-15/aom-and-av1.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-01-14/erlang-record-to-map.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-01-13/formdata-urlsearchparams.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-01-12/let-it-bookmarklet.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2018-01-05/sdp-unified-plan.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-12-31/end-of-2017.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-12-30/resize-observer-and-element-query.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-12-12/whatwg-working-mode-changes.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-12-06/font-display.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-10-31/houdini-paint-api.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-10-09/css-rhythmic-sizing.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-09-27/example-local-test-domains.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-09-26/random-str-in-js.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-09-19/remove-foreign-fetch.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-08-19/content-encoding-brotli.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-08-15/universal-mjs-ecosystem.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-08-10/promise-finally-proposal.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-08-05/navigation-preload.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-07-19/aborting-fetch.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-07-14/net-neutrality.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-07-10/subclassible-eventtarget.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-06-21/nomodule-attribute.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-06-12/web-budget-api.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-06-06/webrtc-in-safari11.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-05-22/webrtc-loadmap.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-05-18/gen_statem.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-05-10/web-share.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-03-02/unicode-in-javascript.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-02-21/monthly-web-201702.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-02-17/polyfill-implementation-guideline.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-02-13/csp-report-case-study.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-01-27/monthly-web-201701.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2017-01-10/mixed-contents.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-12-31/end-of-2016.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-12-16/103-early-hints.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-12-12/foreign-fetch.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-12-11/link-rel-service-worker.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-10-27/whatwg-url.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-09-29/vender-prefix-to-origin-trials.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-08-30/be-a-google-developer-experts.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-08-22/websocket-connectivity.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-08-05/sql-for-file-search.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-07-21/fetch-progress-cancel.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-07-12/cache-control-immutable.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-06-25/intersection-observer.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-06-20/mozaicfm-v2.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-06-12/noopener.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-06-09/passive-event-listeners.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-04-24/service-worker-tutorial.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-04-16/stale-while-revalidate.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-04-11/strict-transport-security.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-04-09/public-key-pinning.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-03-30/content-security-policy.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-03-27/svg-font-base-ui.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-03-26/webp.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-03-25/picture.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-03-24/optimize-image.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-03-14/web-font-noto-sans.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-03-04/preload.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-02-26/jsonld-opengraph.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-02-17/content-encoding-zopfli.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-02-15/loading-css-over-http2.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-02-11/resource-hints.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-02-09/atom-feed.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-02-08/h2o-http2-deploy.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-02-01/amp-html.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-01-28/html-compression.amp.html
./google-amp-update-cache.sh https://blog.jxck.io/entries/2016-01-27/new-blog-start.amp.html
